// @/services/promptKeywords.js

export const promptCategories = [
  {
    name: { zh: '画面优化', en: 'Image Optimization' },
    subcategories: [
      {
        name: { zh: '画质提升', en: 'Quality Enhancement' },
        keywords: [
          { zh: '大师作品', en: 'masterpiece' },
          { zh: '最好画质', en: 'best quality' },
          { zh: '更高质量', en: 'high quality' },
          { zh: '更多细节', en: 'detailed' },
          { zh: '超高分辨率', en: 'ultra-high resolution' },
          { zh: '最高分辨率', en: 'highest resolution' },
          { zh: '8k分辨率', en: '8k resolution' },
          { zh: '胶片颗粒', en: 'film grain' },
          { zh: '完美的图像', en: 'perfect illustration' },
        ],
      },
      {
        name: { zh: '渲染优化', en: 'Render Optimization' },
        keywords: [
          { zh: '3d渲染', en: '3d render' },
          { zh: 'unity 渲染', en: 'unity render' },
          { zh: 'C4D渲染', en: 'c4d render' },
          { zh: 'unreal engine 渲染', en: 'unreal engine render' },
          { zh: 'sketchup 渲染', en: 'sketchup render' },
          { zh: 'blender 渲染', en: 'blender render' },
        ],
      },
    ],
  },
  {
    name: { zh: '镜头视角', en: 'Lens & View' },
    subcategories: [
      {
        name: { zh: '镜头类型', en: 'Lens Type' },
        keywords: [
          { zh: '全景', en: 'full shot' },
          { zh: '中景镜头', en: 'medium shot' },
          { zh: '长焦镜头', en: 'telephoto lens' },
          { zh: '微距镜头', en: 'macro lens' },
          { zh: '鱼眼镜头', en: 'fisheye lens' },
          { zh: '全身像', en: 'full body shot' },
          { zh: '半身像', en: 'cowboy shot' },
          { zh: '特写像', en: 'close-up shot' },
          { zh: '景深', en: 'depth of field' },
          { zh: '单人', en: 'solo' },
          { zh: '上半身', en: 'upper body' },
          { zh: '主观视角', en: 'pov' },
          { zh: '横向背景', en: 'landscape' },
        ],
      },
      {
        name: { zh: '视角构图', en: 'View & Composition' },
        keywords: [
          { zh: '鸟瞰', en: 'from above' },
          { zh: '正视', en: 'straight-on' },
          { zh: '侧视', en: 'from side' },
          { zh: '仰视', en: 'from below' },
          { zh: '完美构图', en: 'perfect composition' },
          { zh: '中心构图', en: 'centered' },
          { zh: '俯视视角', en: 'top-down view' },
          { zh: '仰视视角', en: 'worms-eye view' },
          { zh: '变焦图层', en: 'zoom layer' },
          { zh: '分镜', en: 'sequence' },
        ],
      },
    ],
  },
  {
    name: { zh: '色彩光线', en: 'Color & Light' },
    subcategories: [
      {
        name: { zh: '色彩色调', en: 'Color Tone' },
        keywords: [
          { zh: '冷色调', en: 'cold tones' },
          { zh: '暖色调', en: 'warm tones' },
          { zh: '柔和色调', en: 'soft colors' },
          { zh: '鲜艳色调', en: 'vibrant colors' },
          { zh: '单色', en: 'monochrome' },
          { zh: '高对比度', en: 'high contrast' },
          { zh: '高饱和度', en: 'high saturation' },
          { zh: '低饱和度', en: 'low saturation' },
        ],
      },
      {
        name: { zh: '光线效果', en: 'Lighting Effects' },
        keywords: [
          { zh: '日光', en: 'sunlight' },
          { zh: '柔光', en: 'soft light' },
          { zh: '逆光', en: 'backlight' },
          { zh: '工作室照明', en: 'studio lighting' },
          { zh: '史诗般的灯光', en: 'epic lighting' },
          { zh: '电影级光照', en: 'cinematic lighting' },
          { zh: '戏剧性照明', en: 'dramatic lighting' },
          { zh: '霓虹光照', en: 'neon lighting' },
        ],
      },
    ],
  },
  {
    name: { zh: '艺术风格', en: 'Art Style' },
    subcategories: [
      {
        name: { zh: '艺术类型', en: 'Art Type' },
        keywords: [
          { zh: '铅笔画', en: 'pencil sketch' },
          { zh: '彩色铅笔画', en: 'colored pencil sketch' },
          { zh: '水彩', en: 'watercolor' },
          { zh: '油画', en: 'oil painting' },
          { zh: '蜡笔画', en: 'crayon painting' },
          { zh: '马克笔', en: 'marker art' },
          { zh: '剪纸', en: 'paper cutting' },
          { zh: '插画', en: 'illustration' },
        ],
      },
      {
        name: { zh: '艺术流派', en: 'Art Movement' },
        keywords: [
          { zh: '文艺复兴风格', en: 'renaissance style' },
          { zh: '哥特风格', en: 'gothic style' },
          { zh: '洛可可风格', en: 'rococo style' },
          { zh: '印象主义', en: 'impressionism' },
          { zh: '抽象主义', en: 'abstract art' },
          { zh: '超写实主义', en: 'hyperrealism' },
          { zh: '蒸汽朋克', en: 'steampunk' },
          { zh: '赛博朋克', en: 'cyberpunk' },
        ],
      },
      {
        name: { zh: '艺术大师', en: 'Art Masters' },
        keywords: [
          { zh: '达芬奇', en: 'by Leonardo da Vinci' },
          { zh: '莫奈', en: 'by Claude Monet' },
          { zh: '梵高', en: 'by Vincent van Gogh' },
          { zh: '毕加索', en: 'by Pablo Picasso' },
          { zh: '达利', en: 'by Salvador Dalí' },
          { zh: '安迪沃霍尔', en: 'by Andy Warhol' },
          { zh: '安藤忠雄', en: 'by Tadao Ando' },
          { zh: '扎哈哈迪德', en: 'by Zaha Hadid' },
          { zh: '宫崎骏', en: 'by Hayao Miyazaki' },
          { zh: '新海诚', en: 'by Makoto Shinkai' },
          { zh: '皮克斯', en: 'by Pixar' },
          { zh: '迪士尼', en: 'by Disney' },
        ],
      },
    ],
  },
  {
    name: { zh: '环境描述', en: 'Environment' },
    subcategories: [
      {
        name: { zh: '日夜四季', en: 'Time & Season' },
        keywords: [
          { zh: '春天', en: 'spring' },
          { zh: '夏天', en: 'summer' },
          { zh: '秋天', en: 'autumn' },
          { zh: '冬天', en: 'winter' },
          { zh: '黄昏', en: 'dusk' },
          { zh: '夜晚', en: 'night' },
          { zh: '多云', en: 'cloudy' },
          { zh: '雨天', en: 'rainy' },
          { zh: '大雾', en: 'foggy' },
          { zh: '冰雪', en: 'ice and snow' },
          { zh: '闪电', en: 'lightning' },
          { zh: '彩虹', en: 'rainbow' },
          { zh: '霞光', en: 'morning glow' },
        ],
      },
      {
        name: { zh: '自然环境', en: 'Nature' },
        keywords: [
          { zh: '太空', en: 'space' },
          { zh: '月球', en: 'moon' },
          { zh: '大海', en: 'ocean' },
          { zh: '海边', en: 'seaside' },
          { zh: '森林', en: 'forest' },
          { zh: '沙漠', en: 'desert' },
          { zh: '草原', en: 'grassland' },
          { zh: '山丘', en: 'hill' },
          { zh: '峡谷', en: 'canyon' },
          { zh: '湖泊', en: 'lake' },
          { zh: '溪流', en: 'stream' },
          { zh: '瀑布', en: 'waterfall' },
          { zh: '花海', en: 'sea of flowers' },
          { zh: '田野', en: 'field' },
          { zh: '牧场', en: 'pasture' },
          { zh: '竹林', en: 'bamboo forest' },
          { zh: '电', en: 'electric' },
        ],
      },
      {
        name: { zh: '人造环境', en: 'Man-made' },
        keywords: [
          { zh: '太空舱', en: 'space capsule' },
          { zh: '城市天际线', en: 'city skyline' },
          { zh: '城堡', en: 'castle' },
          { zh: '博物馆', en: 'museum' },
          { zh: '体育场', en: 'stadium' },
          { zh: '游乐园', en: 'amusement park' },
          { zh: '寺庙', en: 'temple' },
          { zh: '飞机场', en: 'airport' },
          { zh: '火车站', en: 'train station' },
          { zh: '咖啡馆', en: 'cafe' },
          { zh: '酒店大堂', en: 'hotel lobby' },
          { zh: '酒吧', en: 'bar' },
          { zh: '美食餐厅', en: 'restaurant' },
          { zh: '购物商场', en: 'shopping mall' },
          { zh: '室内', en: 'indoor' },
          { zh: '客厅', en: 'living room' },
          { zh: '餐厅', en: 'dining room' },
          { zh: '卧室', en: 'bedroom' },
          { zh: '街道', en: 'street' },
          { zh: '魔法阵', en: 'magic circle' },
        ],
      },
      {
        name: { zh: '节日气氛', en: 'Festivals' },
        keywords: [
          { zh: '春节', en: 'Spring Festival' },
          { zh: '圣诞节', en: 'Christmas' },
          { zh: '中秋节', en: 'Mid-Autumn Festival' },
          { zh: '万圣节', en: 'Halloween' },
        ],
      },
    ],
  },
  {
    name: { zh: '人物形象', en: 'Characters' },
    subcategories: [
      {
        name: { zh: '发型发色', en: 'Hair' },
        keywords: [
          { zh: '短发', en: 'short hair' },
          { zh: '中等长度头发', en: 'medium hair' },
          { zh: '长发', en: 'long hair' },
          { zh: '刘海', en: 'bangs' },
          { zh: '眼间刘海', en: 'hair between eyes' },
          { zh: '遮住单眼', en: 'hair over one eye' },
          { zh: '金发', en: 'blonde hair' },
          { zh: '银发', en: 'silver hair' },
          { zh: '黑发', en: 'black hair' },
          { zh: '赤发', en: 'red hair' },
          { zh: '马尾', en: 'ponytail' },
          { zh: '双马尾', en: 'twintails' },
          { zh: '呆毛', en: 'ahoge' },
          { zh: '颤动的头发', en: 'wavy hair' },
          { zh: '散开的头发', en: 'disheveled hair' },
          { zh: '湿发', en: 'wet hair' },
        ],
      },
      {
        name: { zh: '五官表情', en: 'Facial Features' },
        keywords: [
          { zh: '金瞳', en: 'golden eyes' },
          { zh: '红瞳', en: 'red eyes' },
          { zh: '蓝瞳', en: 'blue eyes' },
          { zh: '异色瞳', en: 'heterochromia' },
          { zh: '苍白皮肤', en: 'pale skin' },
          { zh: '深色皮肤', en: 'dark skin' },
          { zh: '闭眼', en: 'closed eyes' },
          { zh: '眼泪', en: 'tears' },
          { zh: '张嘴', en: 'open mouth' },
          { zh: '嘴唇微张', en: 'parted lips' },
        ],
      },
      {
        name: { zh: '服饰穿搭', en: 'Clothing' },
        keywords: [
            { zh: '女巫帽', en: 'witch hat' },
            { zh: '白衬衫', en: 'white shirt' },
            { zh: '皮夹克', en: 'leather jacket' },
            { zh: '大衣', en: 'coat' },
            { zh: '水手服', en: 'sailor suit' },
            { zh: '西装', en: 'suit' },

        ]
      }
    ]
  }
]; 